### ISSUE TITLE
aws 개인과제 실습

### ISSUE THREAD

**Issue by yunjushin** [yunjushin/maskShop-syj#2]
skccuser11/skcc!23
us-east-1

aws configure

eksctl create cluster --name skccuser11-Cluster --version 1.15 --nodegroup-name standard-workers --node-type t3.medium --nodes 3 --nodes-min 1 --nodes-max 3

aws eks --region us-east-1 update-kubeconfig --name skccuser11-Cluster

aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-order

AWS -> ECR 에서 각 MSA 별 리파지토리 생성

cd ~
mkdir maskShop
cd maskShop

git clone https://github.com/wjdwodnrdl/maskshop_team_final  -- git 에 있는 소스를 로컬에 clone

export ECR=496278789073.dkr.ecr.us-east-2.amazonaws.com/skccteam3-order

각 msa 폴더로 가서 패키지->빌드->푸시

mvn package
docker build -t 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-order:v1 .
docker push 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-order:v1

496278789073.dkr.ecr.us-east-2.amazonaws.com/skccteam3-delivery
docker build -t 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-delivery:v1 .
docker push 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-delivery:v1

496278789073.dkr.ecr.us-east-2.amazonaws.com/skccteam3-inventory
docker build -t 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-inventory:v1 .
docker push 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-inventory:v1

496278789073.dkr.ecr.us-east-2.amazonaws.com/skccteam3-mypage
docker build -t 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-mypage:v1 .
docker push 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-mypage:v1

496278789073.dkr.ecr.us-east-2.amazonaws.com/skccteam3-gateway
docker build -t 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-gateway:v1 .
docker push 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-gateway:v1

496278789073.dkr.ecr.us-east-2.amazonaws.com/skccteam3-product
docker build -t 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-product:v1 .
docker push 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-product:v1

docker build -t 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-adminpage:v1 .
docker push 052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-adminpage:v1

kubectl create deploy order --image=052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-order:v1 
kubectl create deploy delivery --image=052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-delivery:v1
kubectl create deploy inventory --image=052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-inventory:v1 
kubectl create deploy mypage --image=052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-mypage:v1 
kubectl create deploy gateway --image=052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-gateway:v1 

kubectl create deploy product --image=052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-product:v1 
kubectl create deploy adminpage --image=052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-adminpage:v1 

kubectl expose deploy order --type=ClusterIP --port=8080

** 카프카 확인
kubectl -n kafka exec -ti my-kafka-0 -- /usr/bin/kafka-console-consumer --bootstrap-server my-kafka:9092 --topic maskShop3 --from-beginning

버전 2 로 변경되었을때 kubectl 로 이미지 교체:  kubectl set image deploy gateway skccuser11-gateway=052937454741.dkr.ecr.us-east-1.amazonaws.com/skccuser11-gateway:v2
이미지 버전 교체 확인: kubectl get deploy gateway -o yaml

** 로그 보기
skccadmin@SKCC16D00067:~$ kubectl get pod

NAME                        READY   STATUS    RESTARTS   AGE
delivery-b5f7ddc75-2qnhz    1/1     Running   0          72m
gateway-5f8d58678b-8rt64    1/1     Running   0          17m
httpie                      1/1     Running   0          80m
inventory-6655d4969-4xspm   1/1     Running   0          72m
mypage-76459b5994-4cqjm     1/1     Running   0          72m
order-66bf689b6d-ft4cs      1/1     Running   0          13m

skccadmin@SKCC16D00067:~$ kubectl logs order-66bf689b6d-ft4cs

http POST a87c7d717dc8845d9b4f3e40fb13777d-909845615.us-east-1.elb.amazonaws.com:8080/orders orderId=1111 productId=1111 qty=10
http PATCH acf49635abb1c462c9da32cf6e14e749-276510094.us-east-2.elb.amazonaws.com:8080/orders orderId=1111 productId=1111 qty=10 type="cancel"

http POST a87c7d717dc8845d9b4f3e40fb13777d-909845615.us-east-1.elb.amazonaws.com:8080/products productId=1234 productName=test invQty=100
http PATCH a87c7d717dc8845d9b4f3e40fb13777d-909845615.us-east-1.elb.amazonaws.com:8080/products/1 productId=1234 invQty=20

** product 에 istio 적용​

1. istio 설치
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.4.3 sh -

cd istio-1.4.3
export PATH=$PWD/bin:$PATH
for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
kubectl apply -f install/kubernetes/istio-demo.yaml

2. product, inventory 에 적용
kubectl get deploy product -o yaml > product_deploy.yaml
kubectl apply -f <(istioctl kube-inject -f product_deploy.yaml)

kubectl get deploy inventory -o yaml > inventory_deploy.yaml
kubectl apply -f <(istioctl kube-inject -f inventory_deploy.yaml)

*** 아래는 들여쓰기가 되어야 하니 workflow 에서 검색하여 복붙

kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: inventory
spec:
  host: inventory
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 2
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutiveErrors: 5
      interval: 1s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
EOF

3. httpie 설치

httpie 설치 (*** 아래는 들여쓰기가 되어야 하니 workflow 에서 검색하여 복붙)

cat <<EOF | kubectl apply -f -
apiVersion: "v1"
kind: "Pod"
metadata: 
  name: httpie
  namespace: default
  labels: 
    name: httpie
spec: 
  containers: 
    - name: httpie
      image: clue/httpie
      command:
        - sleep
        - "360000"
EOF

4. kubectl exec -it httpie bin/bash 

5. seige 설치
apt-get update -y
apt-get install -y siege

6. seige툴로 부하 발생
siege -c10 -t10S -v --content-type "application/json" 'http://product:8080/products POST {"productId":1111,"productName":1111,"invQty":20}'​

** 부하 발생 시 socket 에러 발생하면 replicaset 두개 떠있는거 중 0인거 삭제

결과

Transactions:                     79 hits
Availability:                  49.38 %
Elapsed time:                   9.02 secs
Data transferred:               0.02 MB
Response time:                  0.05 secs
Transaction rate:               8.76 trans/sec
Throughput:                     0.00 MB/sec
Concurrency:                    0.46
Successful transactions:          79
Failed transactions:              81
Longest transaction:            0.15
Shortest transaction:           0.02

FILE: /var/log/siege.log
You can disable this annoying message by editing
the .siegerc file in your home directory; change
the directive 'show-logfile' to false.
root@httpie:/#

7. 확인 후 제거를 하면
kubectl delete DestinationRule inventory

Lifting the server siege...      done.

Transactions:                     92 hits
Availability:                  55.76 %  <--- 위에거보다 높게 나오면 됨
Elapsed time:                   9.12 secs
Data transferred:               0.02 MB
Response time:                  0.04 secs
Transaction rate:              10.09 trans/sec
Throughput:                     0.00 MB/sec
Concurrency:                    0.37
Successful transactions:          92
Failed transactions:              73
Longest transaction:            0.09
Shortest transaction:           0.02

** autoscaling

1. 설정
kubectl autoscale deployment product--cpu-percent=1 --min=1 --max=10
kubectl autoscale deploy product --min=1 --max=10 --cpu-percent=15 <- cpu 15% 이상이면 replica 를 10개까지 늘려준다.
kubectl get hpa product -o yaml

2. 부하
siege -v -c100 -t60S -r180 --content-type "application/json" 'http://product:8080/orders POST {"productId":1111, "productName":"1111", "qty":"1000"}'
<- 워크로드를 2분간 걸어준다.

3. 모니터링
kubectl get deploy product -w <- 모니터링: 스케일아웃 확인

siege 로그
Lifting the server siege...      done.

Transactions:                  12446 hits
Availability:                 100.00 %
Elapsed time:                  59.70 secs
Data transferred:               2.81 MB
Response time:                  3.75 secs
Transaction rate:             208.48 trans/sec
Throughput:                     0.05 MB/sec
Concurrency:                  781.58
Successful transactions:       12446
Failed transactions:               0
Longest transaction:           13.42
Shortest transaction:           0.06

-FILE: /var/log/siege.log
You can disable this annoying message by editing
the .siegerc file in your home directory; change
the directive 'show-logfile' to false.

4. pod 가 늘어난 것을 확인해야하지만 안늘어남.
모든 호출이 정상이고 (이전에는 socket 에러 발생하였음) Availability 가 100% 로 확인?????

5. 확인한 후 제거: kubectl delete horizontalpodautoscaler product

** 무정지배포
1. 요청을 계속 날리고 잇기
siege -v -c1 -t300S -r10 --content-type "application/json" 'http://order:8080/orders

2. 중간에 버전 올려서 배포를 하면 실패가 발생

[error] socket: 2033968896 connection refused.: Connection refused
[error] socket: 2000398080 connection refused.: Connection refused
[error] socket: -2000824576 connection refused.: Connection refused
done.
siege aborted due to excessive socket failure; you
can change the failure threshold in $HOME/.siegerc

Transactions:                  12428 hits
Availability:                  91.71 %    <----------100% 에서 떨어진 것 확인
Elapsed time:                  97.66 secs
Data transferred:               2.81 MB
Response time:                  0.24 secs
Transaction rate:             127.26 trans/sec
Throughput:                     0.03 MB/sec
Concurrency:                   30.38
Successful transactions:       12428
Failed transactions:            1123
Longest transaction:            1.31
Shortest transaction:           0.01

3. 이를 막기위해 Readiness Probe 를 설정
******************** 여기서부터 해야함 *****************

**Comment by wjdwodnrdl** [comment]
인벤토리 폴리시핸들러에 아래 부분 변경하시면 됩니다

//0805 lys수정 start + jjw수정
    @StreamListener(KafkaProcessor.INPUT)
    public void wheneverProductModified_Change(@Payload ProductModified productModified){
              Inventory inventory = new Inventory();
        if(inventoryRepository.findByProductId(productModified.getProductId()).isPresent()) {

           System.out.println("##### listener INVENTORY MODIFIED  : " + productModified.toJson());


            inventory = inventoryRepository.findByProductId(productModified.getProductId()).get();
            inventory.setInvQty(productModified.getInvQty());
            inventoryRepository.save(inventory);
        }

        else {
            System.out.println("##### listener INVENTORY INSERT ======================");

            inventory.setProductId(productModified.getProductId());
            inventory.setInvQty(productModified.getInvQty());
            inventoryRepository.save(inventory);
        }
    }
//0805 lys수정 end
